apiVersion: v1
kind: ServiceAccount
metadata:
  name: gari-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gari-controller
rules:
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["httproutes", "gateways", "gatewayclasses"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gateways/status", "gatewayclasses/status", "httproutes/status"]
  verbs: ["update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gari-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gari-controller
subjects:
- kind: ServiceAccount
  name: gari-controller
  namespace: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: reference-class
spec:
  controllerName: github.com/gke-labs/gateway-api-reference-implementation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gari-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gari-controller
  template:
    metadata:
      labels:
        app: gari-controller
    spec:
      serviceAccountName: gari-controller
      containers:
      - name: controller
        image: gari-controller:latest
        imagePullPolicy: IfNotPresent
        args: ["--proxy-bind-address", ":8000"]
        ports:
        - containerPort: 8000
          name: proxy
---
apiVersion: v1
kind: Service
metadata:
  name: gari-proxy
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: gari-controller
  ports:
  - port: 80
    targetPort: 8000
